### ISSUE TITLE
Does not read all records

### ISSUE THREAD

**Issue by jonimnim** [spidru/JGribX#1]
When I try to read a grab file, I get "Records successfully read: 1 of 195". What does "RecordsSkipped" mean?

**Comment by spidru** [comment]
The decoder skips a record when it does not recognize its format, or when it contains certain parameters which are currently not supported. Could you post the full console output you are receiving?

**Comment by jonimnim** [comment]
This is a full display console.
```
JGribX version 0.3-180529
INFO: GRIB Record 1
INFO: 	Reference Time: Wed Jun 06 00:00:00 UTC 2018
INFO: 	Parameter: missing (missing parameter)
INFO: 	Level: DBSL (0 m below sea level)
WARNING: Skipping GRIB record 2 (Record does not have a valid GRIB header)
WARNING: Skipping GRIB record 3 (Record does not have a valid GRIB header)
WARNING: Skipping GRIB record 4 (Record does not have a valid GRIB header)
WARNING: Skipping GRIB record 5 (Record does not have a valid GRIB header)
...
WARNING: Skipping GRIB record 195 (Record does not have a valid GRIB header)
INFO: Reached end of file: 1 of 195 records read successfully
---------------------------------------
Reading file: /home/joni/NetBeansProjects/grib_reader/data/baltic-sea-currents.grb
GRIB Edition: 1
Records successfully read: 1 of 195
---------------------------------------
Weather Centre(s): 0 [Reserved]
Generating Process(es): 0 [Reserved]
Forecast Time(s): 
	06-06-2018 00:00:00 UTC
Reference Time: 
	06-06-2018 00:00:00 UTC
Data: 
	missing: DBSL:0
```

Then I looked at the GRIB file and saw that there was another byte between "7777" and the next "GRIB". I tried to make in the code so that this byte was omitted, then everything seemed normal. But there are files with 6 extra bytes between "7777" and "GRIB".

**Comment by spidru** [comment]
Thanks for the info. It seems that any extra bytes between the end of one record and the start of the next record are not being handled well by the decoder. I will look into this later today. I would appreciate if you could send me one such GRIB file causing problems so that I can use this for testing. Thanks.

**Comment by jonimnim** [comment]
Where can I send you an example of a file?

**Comment by spidru** [comment]
You can attach files in comments here

**Comment by jonimnim** [comment]
Now I read both files. Just in case I'm sending you an example of these file in an attachment.

[baltic-sea-currents.grb.zip](https://github.com/spidru/JGribX/files/2086737/baltic-sea-currents.grb.zip)
