### ISSUE TITLE
Build's tests failed and code does not work, both due to NoValidGribException on valid GRIB2 files

### ISSUE THREAD

**Issue by Timelessprod** [spidru/JGribX#16]
Hi.

I downloaded the actual source code (commit [0e5b8c3](https://github.com/spidru/JGribX/commit/0e5b8c3e2d1b52cb9578bda811ac30b6ad2ab15e) and try to build it with gradle on Intellij. When doing it, all two thirdof the tests failed due to `NoValidGribException`. Here is the compilation output on Intellij console :
```txt
15:52:50: Executing task 'build'...

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test

mt.edu.um.cf2.jgribx.GribTest > testVersion STARTED

mt.edu.um.cf2.jgribx.GribTest > testVersion PASSED

mt.edu.um.cf2.jgribx.GribTest > testGrib1Gfs3 STARTED

mt.edu.um.cf2.jgribx.GribTest > testGrib1Gfs3 FAILED
    mt.edu.um.cf2.jgribx.NoValidGribException at GribTest.java:58

mt.edu.um.cf2.jgribx.GribTest > testGrib2Gfs3 STARTED

mt.edu.um.cf2.jgribx.GribTest > testGrib2Gfs3 FAILED
    mt.edu.um.cf2.jgribx.NoValidGribException at GribTest.java:163

3 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///C:/Users/amerat/Downloads/JGribX-master/JGribX-master/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
6 actionable tasks: 1 executed, 5 up-to-date
15:52:54: Task execution finished 'build'.
```

I thought it was due to corrupted GRIB files in your repository, but when I try with my own and with the JAR I built from the actual code (not your release), it fails too giving me this error :
```txt
mt.edu.um.cf2.jgribx.NoValidGribException: No valid GRIB records found.
	at mt.edu.um.cf2.jgribx.GribFile.<init>(GribFile.java:138)
	at mt.edu.um.cf2.jgribx.GribFile.<init>(GribFile.java:80)
	at mt.edu.um.cf2.jgribx.GribFile.<init>(GribFile.java:63)
```
The GRIB2 file I use is not corrupted, I can open it in Nasa's Panoply GUI Software without any error. Reading your [GribFile.java:138](https://github.com/spidru/JGribX/blob/0e5b8c3e2d1b52cb9578bda811ac30b6ad2ab15e/src/main/java/mt/edu/um/cf2/jgribx/GribFile.java#L138), it looks like the code is seeing an empty record whereas it is not.

In my GRIB2 file, there's only one data `Temperature_height_above_ground` at only one timestamp `2021-10-12 14:00+0000` and height `2.00000 m`, thus I wrote the code below.

Please note that the GRIB2 data is first acquired by a client API so that's why it's first held by a variable `bytes` which type is `Array[Byte]`. Before using your library I write the GRIB2 data to a file and then pass it's path to the `GribFile` constructor. This part of the code works fine, I can open the created file in Nasa's Panoply.

```scala
      import mt.edu.um.cf2.jgribx._
      import java.util.Calendar
      import java.util.GregorianCalendar
      
      val path: String = "mf-data.grb2"
      val file: File = new File(path)
      FileUtils.writeByteArrayToFile(file, bytes)
      
      val gribFile: GribFile = new GribFile(path)
      
      val date: Calendar = new GregorianCalendar(2021, Calendar.OCTOBER, 12, 14, 0, 0)
      val parameter: String = "TMP"
      val ltvid: String = "TGL:2"     // TGL = "specified height level above ground" & 2 = 2 meters
      val lat: Double = 50.7
      val lon: Double = 362.29
      
      val record: GribRecord = gribFile.getRecord(date, parameter, ltvid)
      val value: Double = record.getValue(lat, lon)
      println("Value at (" + lat + ", " + lon + ") : " + value + "\n")
```

Thanks.

**Comment by Timelessprod** [comment]
@spidru Here is the GRIB2 file I'm using : https://we.tl/t-l3xbpVrYUv
Thanks

**Comment by spidru** [comment]
Hi @Timelessprod, thanks for sending the file. The issue is that the GRIB file seems to use Simple Packing in its DRS section, whereas at the moment only Complex Packing and Spatial Differencing is supported for GRIB2. I'll try to find some time to implement Simple Packing, shouldn't be too much work.

**Comment by Timelessprod** [comment]
> 
> 
> Hi @Timelessprod, thanks for sending the file. The issue is that the GRIB file seems to use Simple Packing in its DRS section, whereas at the moment only Complex Packing and Spatial Differencing is supported for GRIB2. I'll try to find some time to implement Simple Packing, shouldn't be too much work.

@spidru Thanks for your reply and for adapting your library. Do you have an idea of when it would be ready ? So I can tell my manager when my product will be available.

Thank you very much.

**Comment by spidru** [comment]
Hmm not quite sure how I would go about that serializable issue. If it's a blocking issue let me know and I'll have to look into it in some detail.

In the meantime, I'll find some time this week to have a look at your new GRIB file. Most probably there's something which is not yet supported. You can actually check that using the JGribX CLI as follows: ```java -jar JGribX.jar -i inputfile.grb2 -l 4```.

**Comment by spidru** [comment]
Hi @Timelessprod, apologies for the long delay. Is this issue still relevant? If so, could you please re-share the GRIB file giving you a ```NoValidGribException```?

**Comment by Timelessprod** [comment]
Hi @spidru I'm sorry to tell you that I have no longer access to this file as it was on my professional computer and that my internship has ended 5 months ago. I'm sorry for the inconvenience.
