### ISSUE TITLE
NoValidGribException: No valid GRIB records found.

### ISSUE THREAD

**Issue by gaci0703** [spidru/JGribX#20]
Hello.
I currently pull my grib2 data from https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/MT.gfs_CY.00/RD.20220705/PT.grid_DF.gr2/.  When I put this data into a GribFile, I get the NoValidGribException.  I am using the current version of the JGribX.jar.  After downloading one of these records from this url, I also checked using java -jar JGribX.jar -i grib2.grb and I get the same NoValidGribException.  Can you please tell me what is wrong with this data?

Thank you.

**Comment by gaci0703** [comment]
Thank you.  I am hoping that url that contains the grib2 files is helping you with the updates.

**Comment by spidru** [comment]
Hi @gaci0703,

I finally have a new version for you to test. Could you try it out? It requires JRE 8 or higher.

https://output.circle-artifacts.com/output/job/70d21686-98f4-40d3-89e5-7f8ad42aaf77/artifacts/0/build/libs/JGribX.jar

**Comment by gaci0703** [comment]
Hello @spidru,
It works perfectly on the gfs wind data from this directory -  https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/MT.gfs_CY.00/RD.20220705/PT.grid_DF.gr2/.  When I try the new update on RAP or NAM wind data, I get the NoValidGribException.  I would assume GFS, RAP, and NAM are all in the same format.
https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/MT.rap_CY.06/RD.20220725/PT.grid_DF.gr2/ - for RAP and                             https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/MT.nam_AR.ak_CY.06/RD.20220725/PT.grid_DF.gr2/ for NAM

**Comment by spidru** [comment]
Hi @gaci0703,

Thanks for confirming that at least the original issue (i.e. unsupported quasi-regular grids and JPEG 2000 encoded data) has been resolved. I would therefore like to close this issue and kindly ask you to open a new one.

But to already give some feedback, I noticed that all 3 gr2 files you linked in your last message do not work for me. Could you resend them (in a new issue) as attachments? Thanks!

**Comment by gaci0703** [comment]
I opened a new issue - Thank you!!!

**Comment by spidru** [comment]
Merged to master with b99d8a5.
