### ISSUE TITLE
getRecord does not work with level without level value

### ISSUE THREAD

**Issue by pavelber** [spidru/JGribX#3]
I have GRB1 file with SFC level, but without level value.

- If I search for records with "SFC", it does not find any record, because 
src/main/mt/edu/um/cf2/jgribx/GribFile.java:359 `if (matcher.find())` is false
- if I put "SFC:0" it does not find any record because `record.getLevelValues()[0]` is NaN
- if I put "SFC:", it fails with 
`
Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at mt.edu.um.cf2.jgribx.GribFile.getRecord(GribFile.java:364)
`

**Comment by spidru** [comment]
Hi @pavelber,

Apologies for the delay, I hadn't checked this repo in a while. I'll see if I can carve out some time to take a look at this over the next few days.

**Comment by spidru** [comment]
Hi @pavelber,

I had a quick look at the code. Indeed the code is not handling level values without colons such as "SFC" properly. Will push a fix in a few moments.

**Comment by spidru** [comment]
Fix pushed: bb6eece65e8d575d573993cb122780a8f156bcf3

Could you please verify?

**Comment by pavelber** [comment]
Works, thanx!
